changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - bot-user-name

  categories:
    - title: 'Features'
      labels:
        - 'feature'
        - 'enhancement'

    - title: 'Bug Fixes'
      labels:
        - 'fix'
        - 'bug'

    - title: 'Dependency Updates'
      labels:
        - 'dependencies'
        - 'renovate'

    - title: 'Maintenance'
      labels:
        - 'chore'
        - 'documentation'
        - 'internal'
